---

java_home: "{{ java8_home }}"

proxy_env:
  dummy: value
  #http_proxy: http://proxy:8080

plugins:
  - 'ansible'
  - 'ansicolor'
#  - 'analysis-collector'
#  - 'analysis-core'    # for findbugs
  - 'artifactory'      # connect to build repository
#  - 'checkstyle'       # source code formatting reports
#  - 'cobertura'
# - 'copyartifact'
  - 'dashboard-view'
# - 'delivery-pipeline-plugin'
#  - 'dependency-check-jenkins-plugin'
#  - 'dry'              # don't repeat yourself
#  - 'findbugs'          # common bugs can be squashed
#  - 'fortify360'
  - 'git'              # connect to git
#  - 'gradle'           # build tool
# - 'jacoco'           # test coverage
#  - 'jira'             # Atlassian Jira API
  - 'jobConfigHistory' # save changes in job configuration
# - 'm2release'
#  - 'parameterized-trigger'
#  - 'pmd'              #
  - 'promoted-builds'
#  - 'release'
  - 'role-strategy'
#  - 'ssh-agent'
  - 'scm-sync-configuration'
  - 'simple-theme-plugin'
#  - 'sonar'            # source code quality
  - 'thinBackup'       # backup job configurations
#  - 'violations'       #
  - 'ws-cleanup'       # Workspace cleanup
#  - 'swarm'     # Swarm plugin for build slaves
#  - 'msbuild'     # Plugin for building Microsoft applications
#  - 'xcode-plugin' # Plugin for building Mac OS X applications

jenkins_base_url: 'http://pkg.jenkins-ci.org/redhat'
jenkins_data: "/home/jenkins"
jenkins_home: "/var/lib/jenkins"
jenkins_http: 8080
jenkins_tools: "{{jenkins_data}}/tools"
jenkins_https: ""
jenkins_cli: '{{ jenkins_data }}/jenkins-cli.jar' # Jenkins CLI executable
updates_dest: '{{ jenkins_data }}/updates_jenkins.json' # Jenkins updates
jenkins_repo: "jenkins.repo"
jenkins_repo_key: "{{jenkins_base_url}}/jenkins-ci.org.key"
jenkins_phrase: "ask_devops"

rpm_dependencies:
  - 'jenkins'
  - 'unzip'
#  - 'sshpass'
#  - 'rpm-build'
#  - 'rpmdevtools'
#  - 'rpmlint'
#  - 'yum-utils'
#  - 'createrepo'

jenkins_configs:
  - 'config.xml'
  - 'hudson.plugins.git.GitSCM.xml'
  - 'hudson.plugins.git.GitTool.xml'
  - 'hudson.tasks.Mailer.xml'
  - 'hudson.tasks.Shell.xml'
  - 'hudson.triggers.SCMTrigger.xml'
  - 'jenkins.model.ArtifactManagerConfiguration.xml'
  - 'jenkins.model.DownloadSettings.xml'
  - 'jenkins.model.JenkinsLocationConfiguration.xml'
  - 'jobConfigHistory.xml'
  - 'nodeMonitors.xml'
  - 'org.jenkinsci.plugins.gitclient.JGitTool.xml'
  - 'org.jenkinsci.plugins.ansible.AnsibleInstallation.xml'
  - 'org.jfrog.hudson.ArtifactoryBuilder.xml'
  - 'org.codefirst.SimpleThemeDecorator.xml'
