---
language: python
python: "2.7"
env:
  - ANSIBLE_VERSION=2.7.5
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  # Install Ansible.
  - pip install ansible==$ANSIBLE_VERSION

  # Install dependencies.
  - ansible-playbook galaxy_import.yml -vv
  - pip install -r requirements.txt

script:
  - ansible --version
  - ansible-playbook --syntax-check provision.yml
  - ansible-playbook --list-hosts provision.yml
