---

- name: 'enable security'
  lineinfile:
    dest: "{{jenkins_data}}/config.xml"
    regexp: '^  <useSecurity>false</useSecurity>'
    line: '  <useSecurity>true</useSecurity>'
    state: present
  tags:
    - jenkins
    - security

- name: 'restart Jenkins once more'
  debug:
    msg: "restart jenkins"
  notify: restart jenkins
